-- ============================================================
-- schema.sql - структура базы CRM: партнеры, справочники, продажи
-- СУБД: PostgreSQL
-- Автор: Danis Arslanov
-- ============================================================

DROP TABLE IF EXISTS sales_history;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS partner_types;

-- Справочник типов: выпадающий список в карточке заполняется отсюда.
CREATE TABLE partner_types (
    type_id   INT          GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR(10)  NOT NULL,

    CONSTRAINT pk_partner_types      PRIMARY KEY (type_id),
    CONSTRAINT uq_partner_types_name UNIQUE (type_name)
);

-- Обязательны по ТЗ только наименование и email, остальные поля карточки
-- можно оставить пустыми.
CREATE TABLE partners (
    partner_id   INT           GENERATED BY DEFAULT AS IDENTITY,
    type_id      INT           NOT NULL,
    company_name VARCHAR(150)  NOT NULL,
    director     VARCHAR(150),
    phone        VARCHAR(20),
    email        VARCHAR(100)  NOT NULL,
    address      VARCHAR(300),
    rating       INT           NOT NULL DEFAULT 0,

    CONSTRAINT pk_partners         PRIMARY KEY (partner_id),
    CONSTRAINT fk_partners_type    FOREIGN KEY (type_id)
        REFERENCES partner_types (type_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_partners_email   UNIQUE (email),
    CONSTRAINT chk_partners_name   CHECK (btrim(company_name) <> ''),
    CONSTRAINT chk_partners_email  CHECK (email LIKE '%_@_%._%'),
    CONSTRAINT chk_partners_phone  CHECK (phone IS NULL OR phone ~ '^\+[0-9]{11,15}$'),
    CONSTRAINT chk_partners_rating CHECK (rating >= 0)
);

CREATE TABLE products (
    product_id   INT           GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_products      PRIMARY KEY (product_id),
    CONSTRAINT uq_products_name UNIQUE (product_name)
);

-- История продаж: из нее считается скидка партнера в реестре.
CREATE TABLE sales_history (
    sale_id    INT   GENERATED BY DEFAULT AS IDENTITY,
    partner_id INT   NOT NULL,
    product_id INT   NOT NULL,
    sale_date  DATE  NOT NULL,
    quantity   INT   NOT NULL,

    CONSTRAINT pk_sales_history         PRIMARY KEY (sale_id),
    CONSTRAINT fk_sales_history_partner FOREIGN KEY (partner_id)
        REFERENCES partners (partner_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sales_history_product FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_sales_history_qty    CHECK (quantity > 0)
);

CREATE INDEX idx_sales_history_partner ON sales_history (partner_id);
