-- ============================================================
-- schema.sql - чистое хранилище: партнеры, номенклатура, история
-- продаж и справочники для расчета материалов
-- СУБД: PostgreSQL
-- Автор: Danis Arslanov
--
-- Скрипт пересоздает все таблицы вместе с данными. После него -
-- reference.sql (справочники), затем импорт выгрузок etl.py.
-- Стиль именования - snake_case.
-- ============================================================

DROP TABLE IF EXISTS sales_history;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS partner_types;
DROP TABLE IF EXISTS material_types;
DROP TABLE IF EXISTS product_types;

-- Организационно-правовая форма вынесена в справочник: в выгрузке она
-- приклеена к названию, и одно и то же «ООО» повторялось бы в каждой строке.
CREATE TABLE partner_types (
    type_id   INT          GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR(10)  NOT NULL,

    CONSTRAINT pk_partner_types      PRIMARY KEY (type_id),
    CONSTRAINT uq_partner_types_name UNIQUE (type_name)
);

-- Адреса, директора, телефона и рейтинга в выгрузке нет: эти поля
-- заполняются в карточке партнера, до тех пор адрес, директор и телефон
-- пустые, а рейтинг 0.
CREATE TABLE partners (
    partner_id   INT           GENERATED BY DEFAULT AS IDENTITY,
    type_id      INT           NOT NULL,
    partner_name VARCHAR(150)  NOT NULL,
    inn          VARCHAR(12)   NOT NULL,
    email        VARCHAR(100)  NOT NULL,
    rating       INT           NOT NULL DEFAULT 0,
    address      VARCHAR(300),
    director     VARCHAR(150),
    phone        VARCHAR(20),

    CONSTRAINT pk_partners         PRIMARY KEY (partner_id),
    CONSTRAINT fk_partners_type    FOREIGN KEY (type_id)
        REFERENCES partner_types (type_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_partners_inn     UNIQUE (inn),
    CONSTRAINT uq_partners_email   UNIQUE (email),
    CONSTRAINT chk_partners_name   CHECK (btrim(partner_name) <> ''),
    CONSTRAINT chk_partners_inn    CHECK (inn ~ '^[0-9]{10}([0-9]{2})?$'),
    CONSTRAINT chk_partners_email  CHECK (email LIKE '%_@_%._%'),
    CONSTRAINT chk_partners_rating CHECK (rating >= 0),
    CONSTRAINT chk_partners_phone  CHECK (phone IS NULL OR phone ~ '^\+[0-9]{11}$')
);

CREATE TABLE products (
    product_id   INT            GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(150)   NOT NULL,
    price        DECIMAL(12,2)  NOT NULL,

    CONSTRAINT pk_products       PRIMARY KEY (product_id),
    CONSTRAINT uq_products_name  UNIQUE (product_name),
    CONSTRAINT chk_products_name CHECK (btrim(product_name) <> ''),
    CONSTRAINT chk_products_price CHECK (price > 0)
);

-- Сумма продажи хранится, хотя сейчас равна количеству на цену: это цена
-- на день сделки, а цена в номенклатуре со временем меняется. Поэтому
-- amount зависит от самой продажи, а не от товара, и 3NF не нарушает.
CREATE TABLE sales_history (
    sale_id    INT            GENERATED BY DEFAULT AS IDENTITY,
    partner_id INT            NOT NULL,
    product_id INT            NOT NULL,
    sale_date  DATE           NOT NULL,
    quantity   INT            NOT NULL,
    amount     DECIMAL(14,2)  NOT NULL,

    CONSTRAINT pk_sales_history          PRIMARY KEY (sale_id),
    CONSTRAINT fk_sales_history_partner  FOREIGN KEY (partner_id)
        REFERENCES partners (partner_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sales_history_product  FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_sales_history_qty     CHECK (quantity > 0),
    CONSTRAINT chk_sales_history_amount  CHECK (amount >= 0)
);

CREATE INDEX idx_sales_history_partner ON sales_history (partner_id);
CREATE INDEX idx_sales_history_product ON sales_history (product_id);

-- Коэффициент типа продукции: множитель расхода материала на единицу.
CREATE TABLE product_types (
    product_type_id INT           GENERATED BY DEFAULT AS IDENTITY,
    type_name       VARCHAR(100)  NOT NULL,
    coefficient     DECIMAL(6,2)  NOT NULL,

    CONSTRAINT pk_product_types              PRIMARY KEY (product_type_id),
    CONSTRAINT uq_product_types_name         UNIQUE (type_name),
    CONSTRAINT chk_product_types_coefficient CHECK (coefficient > 0)
);

-- Процент брака: на столько процентов материала нужно больше чистого расхода.
CREATE TABLE material_types (
    material_type_id INT           GENERATED BY DEFAULT AS IDENTITY,
    type_name        VARCHAR(100)  NOT NULL,
    defect_percent   DECIMAL(5,2)  NOT NULL,

    CONSTRAINT pk_material_types         PRIMARY KEY (material_type_id),
    CONSTRAINT uq_material_types_name    UNIQUE (type_name),
    CONSTRAINT chk_material_types_defect CHECK (defect_percent >= 0 AND defect_percent < 100)
);
