-- ============================================================
-- schema.sql — развёртывание структуры БД (3NF)
-- СУБД: PostgreSQL
-- Именование: snake_case, таблицы во множественном числе
-- ============================================================

-- ------------------------------------------------------------
-- 1. Удаление таблиц с учётом порядка зависимостей
--    (сначала дочерняя deliveries, затем справочники)
-- ------------------------------------------------------------
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

-- ------------------------------------------------------------
-- 2. Создание таблиц
-- ------------------------------------------------------------

-- Партнёры
-- GENERATED BY DEFAULT (а не ALWAYS): при импорте мы подставляем
-- собственные id из файлов, ALWAYS такую вставку запретил бы.
CREATE TABLE partners (
    partner_id    INT           GENERATED BY DEFAULT AS IDENTITY,
    company_name  VARCHAR(150)  NOT NULL,
    inn           VARCHAR(12)   NOT NULL,
    contact_email VARCHAR(100)  NOT NULL,
    phone         VARCHAR(20),
    rating        DECIMAL(3,2),

    CONSTRAINT pk_partners            PRIMARY KEY (partner_id),
    CONSTRAINT uq_partners_inn        UNIQUE (inn),
    CONSTRAINT uq_partners_email      UNIQUE (contact_email),
    CONSTRAINT chk_partners_inn       CHECK (inn ~ '^[0-9]{10}$' OR inn ~ '^[0-9]{12}$'),
    CONSTRAINT chk_partners_email     CHECK (contact_email LIKE '%_@_%._%'),
    CONSTRAINT chk_partners_rating    CHECK (rating IS NULL OR rating BETWEEN 0 AND 5),

    -- Телефон хранится в одном каноническом виде: плюс и только цифры.
    -- В исходнике один номер был записан как '+7 (999) 111-22-33', другой
    -- как '+78125554433' — по таким значениям не работает ни сравнение, ни
    -- поиск. Разделители — дело интерфейса, в базе лежит канон.
    CONSTRAINT chk_partners_phone     CHECK (phone IS NULL OR phone ~ '^\+[0-9]{11,15}$')
);

-- Продукция
CREATE TABLE products (
    product_id   INT           GENERATED BY DEFAULT AS IDENTITY,
    product_name VARCHAR(150)  NOT NULL,

    CONSTRAINT pk_products          PRIMARY KEY (product_id),
    CONSTRAINT uq_products_name     UNIQUE (product_name)
);

-- История отгрузок
CREATE TABLE deliveries (
    sale_id      INT            GENERATED BY DEFAULT AS IDENTITY,
    partner_id   INT            NOT NULL,
    product_id   INT            NOT NULL,
    sale_date    DATE           NOT NULL,
    quantity     INT            NOT NULL,
    total_amount DECIMAL(12,2)  NOT NULL,

    CONSTRAINT pk_deliveries          PRIMARY KEY (sale_id),

    -- RESTRICT: партнёра нельзя удалить, пока есть его отгрузки
    CONSTRAINT fk_deliveries_partner  FOREIGN KEY (partner_id)
        REFERENCES partners (partner_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    -- RESTRICT: товар нельзя удалить, пока он фигурирует в истории
    CONSTRAINT fk_deliveries_product  FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_deliveries_qty     CHECK (quantity > 0),
    CONSTRAINT chk_deliveries_amount  CHECK (total_amount >= 0)
);

-- ------------------------------------------------------------
-- 3. Индексы по внешним ключам (ускоряют JOIN и выборку истории)
-- ------------------------------------------------------------
CREATE INDEX idx_deliveries_partner ON deliveries (partner_id);
CREATE INDEX idx_deliveries_product ON deliveries (product_id);
CREATE INDEX idx_deliveries_date    ON deliveries (sale_date);

-- ------------------------------------------------------------
-- 4. Комментарии к объектам
-- ------------------------------------------------------------
COMMENT ON TABLE  partners             IS 'Партнёры-контрагенты';
COMMENT ON COLUMN partners.inn         IS 'ИНН, 10 или 12 цифр, уникален';
COMMENT ON COLUMN partners.rating      IS 'Рейтинг партнёра от 0 до 5, NULL — не оценён';
COMMENT ON TABLE  products             IS 'Справочник реализуемой продукции';
COMMENT ON TABLE  deliveries           IS 'История отгрузок партнёрам';
COMMENT ON COLUMN deliveries.quantity  IS 'Объём поставки в штуках';
