-- ============================================================
-- schema.sql - структура базы CRM: партнеры, продукция, справочники
-- для расчета материалов, история продаж
-- СУБД: PostgreSQL
-- Автор: Danis Arslanov
--
-- Скрипт пересоздает все таблицы вместе с данными. Чтобы вернуть тестовые
-- данные без пересоздания структуры, достаточно seed.sql.
-- ============================================================

DROP TABLE IF EXISTS sales_history;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS material_types;
DROP TABLE IF EXISTS product_types;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS partner_types;

CREATE TABLE partner_types (
    type_id   INT          GENERATED BY DEFAULT AS IDENTITY,
    type_name VARCHAR(10)  NOT NULL,

    CONSTRAINT pk_partner_types      PRIMARY KEY (type_id),
    CONSTRAINT uq_partner_types_name UNIQUE (type_name)
);

CREATE TABLE partners (
    partner_id   INT           GENERATED BY DEFAULT AS IDENTITY,
    type_id      INT           NOT NULL,
    company_name VARCHAR(150)  NOT NULL,
    director     VARCHAR(150),
    phone        VARCHAR(20),
    email        VARCHAR(100)  NOT NULL,
    address      VARCHAR(300),
    rating       INT           NOT NULL DEFAULT 0,

    CONSTRAINT pk_partners         PRIMARY KEY (partner_id),
    CONSTRAINT fk_partners_type    FOREIGN KEY (type_id)
        REFERENCES partner_types (type_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_partners_email   UNIQUE (email),
    CONSTRAINT chk_partners_name   CHECK (btrim(company_name) <> ''),
    CONSTRAINT chk_partners_email  CHECK (email LIKE '%_@_%._%'),
    CONSTRAINT chk_partners_phone  CHECK (phone IS NULL OR phone ~ '^\+[0-9]{11,15}$'),
    CONSTRAINT chk_partners_rating CHECK (rating >= 0)
);

-- Коэффициент типа продукции: множитель базового расхода материала на единицу.
CREATE TABLE product_types (
    product_type_id INT           GENERATED BY DEFAULT AS IDENTITY,
    type_name       VARCHAR(100)  NOT NULL,
    coefficient     NUMERIC(6,2)  NOT NULL,

    CONSTRAINT pk_product_types             PRIMARY KEY (product_type_id),
    CONSTRAINT uq_product_types_name        UNIQUE (type_name),
    CONSTRAINT chk_product_types_coefficient CHECK (coefficient > 0)
);

-- Процент брака материала: на столько процентов материала нужно больше
-- чистого расхода.
CREATE TABLE material_types (
    material_type_id INT           GENERATED BY DEFAULT AS IDENTITY,
    type_name        VARCHAR(100)  NOT NULL,
    defect_percent   NUMERIC(5,2)  NOT NULL,

    CONSTRAINT pk_material_types        PRIMARY KEY (material_type_id),
    CONSTRAINT uq_material_types_name   UNIQUE (type_name),
    CONSTRAINT chk_material_types_defect CHECK (defect_percent >= 0 AND defect_percent < 100)
);

CREATE TABLE products (
    product_id      INT           GENERATED BY DEFAULT AS IDENTITY,
    product_name    VARCHAR(150)  NOT NULL,
    product_type_id INT           NOT NULL,

    CONSTRAINT pk_products      PRIMARY KEY (product_id),
    CONSTRAINT uq_products_name UNIQUE (product_name),
    CONSTRAINT fk_products_type FOREIGN KEY (product_type_id)
        REFERENCES product_types (product_type_id)
        ON DELETE RESTRICT
);

-- История продаж: из нее строится окно истории и считается скидка партнера.
CREATE TABLE sales_history (
    sale_id    INT   GENERATED BY DEFAULT AS IDENTITY,
    partner_id INT   NOT NULL,
    product_id INT   NOT NULL,
    sale_date  DATE  NOT NULL,
    quantity   INT   NOT NULL,

    CONSTRAINT pk_sales_history         PRIMARY KEY (sale_id),
    CONSTRAINT fk_sales_history_partner FOREIGN KEY (partner_id)
        REFERENCES partners (partner_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_sales_history_product FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_sales_history_qty    CHECK (quantity > 0)
);

CREATE INDEX idx_sales_history_partner ON sales_history (partner_id);
